### ISSUE TITLE
新版本的TS类型可以改成用下划线或者斜体，来和普通变量区分吗？和字符串一样的颜色实在太糟糕了

### ISSUE THREAD

**Issue by sorry77** [tinkertrain/panda-syntax-vscode#59]
这么多年一直用这个配色，有点肌肉记忆，TS类型变成和字符串一样太难受了。

原本字符串是需要特别注意的，现在和TS类型混在一起没有区分度了。

建议保留原有颜色，增加下划线区分会更好一些，下划线可跳转的含义也对应类型的跳转查看。

**Comment by siamak** [comment]
Could you send me a screenshot of your problem?

**Comment by sorry77** [comment]
似乎是多年前的代码最近发布版本导致的。
https://github.com/tinkertrain/panda-syntax-vscode/blob/master/themes/panda-base.yaml
```yaml
# -----------------------------------------------------------------------------
# Name of type (struct, class, etc.)
# -----------------------------------------------------------------------------
# Generic name of type match
- scope: entity.name.type
  settings:
    foreground: _green
    fontStyle: italic
```


这违背了项目中对于颜色的定义，我猜测这是无意的发布。
https://github.com/tinkertrain/panda-syntax-vscode/blob/master/Color%20Semantics.md

before:

<img width="376" alt="Image" src="https://github.com/user-attachments/assets/863dfcd2-e0b9-4b5c-9878-aee52e979154" />

after:
<img width="396" alt="Image" src="https://github.com/user-attachments/assets/c091aec5-0a5a-46d1-bd4e-3acd7d93e4b8" />

version:
<img width="145" alt="Image" src="https://github.com/user-attachments/assets/c2b9ff04-7549-47db-ad22-8e345cf13808" />
